######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 5 22:54:10 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += helloworld.cpp
